typography_spectrum: 0.28896168782375753
color:
  brandStrength: 0.006647932343184948
  lightness: 0.7549477487336844
  saturation: 0.639402997912839
  rhythmicContrast: 0.39204434491693974
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.4928102458361536
name: homesharing
title: homesharing
description: frankfurt am amin
